### PR TITLE
Fixed CLI defaults which overrode those in the coordinator config.

### PR DESCRIPTION
**Pull request by 11xor6**

### CODE REVIEW

**Comment by electrum** [comment]
The overall change of moving the defaults to the coordinator config is correct, but you don't need to assign defaults in the config setter methods. The config system will never inject a null. So, remove the constants (put them inline on the initializers) and verify the defaults in `TestAwsProvisionerConfig` by calling the setters with the same values.

**Comment by electrum** [comment]
See `TestAgentConfig` for an example.

**Comment by 11xor6** [comment]
@electrum I updated the pull request taking your comments into account. I think I understood your comment correctly, but please let me know if I didn't.

**Comment by electrum** [comment]
Looks good, thanks!

**Pull request closed without merging**
